name: pushstrength_flutter_crashlytics
description: Fork of flutter_crashlytics, a Flutter plugin to enable Crashlytics reporting on Android and iOS, also offer the ability to add custom log and informations to the reports.
version: 0.0.1
authors:
- jaumard <jimmy@kiwi-bop.com>
- long1eu <home@long1.eu>
homepage: https://github.com/push-build-user/pushstrength_flutter_crashlytics

dependencies:
  stack_trace: ^1.9.3
  flutter:
    sdk: flutter

environment:
    sdk: ">=2.0.0 <3.0.0"

flutter:
  plugin:
    androidPackage: com.kiwi.fluttercrashlytics
    pluginClass: FlutterCrashlyticsPlugin